
describe('failing test', function () {
  it('fails', function () {
    throw new Error('failure!')
  })
})
